### ISSUE TITLE
exception throwing and rethrowing

### ISSUE THREAD

**Issue by Bobscorn** [Bobscorn/ptop#14]
C++ has no intrinsic stack tracing (without platform specific APIs) nor does it have file/line tracing built into exceptions or seg faults.
In order to throw descriptive exceptions, and record a stack trace we can use nested_exceptions, and some macros.

Proposed: 
try-catch in central functions, frequent functions that call alot of other exception throwing functions and where else needed.
catch any thrown exceptions, and rethrow_with_nested, nesting the call-site/function with the try-catch's name, signature, and context info

Functions proposed:
`void rethrow_with_context(std::string context);`
`void throw_descriptive_exception(std::string error_message, std::string context);`

Macros proposed:
`#define CONTEXT std::string("function: ") + __FUNC__ + " in " + __file__ + ":" + std::to_string(__line__)` <-- example macro definition

Intended usage:
Surround the body of target functions with a try-catch that catches everything, and call `rethrow_with_context(CONTEXT)`
Use `throw_description_exception("example error message", CONTEXT);` instead of explicit exception instantiation

Example use:

```cpp
void some_important_function()
{
    try
    {
        // important stuff
        function_that_might_throw();
    }
    catch (...)
   {
       rethrow_with_context(CONTEXT);
   }
}
```
or
```cpp
void function_that_calls_other_function()
{
    try
    {
        function_that_might_throw();
        function_that_might_throw_also();
        function_that_might_also_throw();
    }
    catch (...)
    {
        throw_with_context(CONTEXT);
    }
}
```

and use throw_descriptive_exception instead of direct exception class

instead of:
`if (result == IMPOSSIBLE_RESULT)
    throw std::runtime_error("world has ended");`

do:
`if (result == IMPOSSIBLE_RESULT)
    throw_descriptive_exception("world has ended", CONTEXT);`

**Comment by DoubleCouponDay** [comment]
completed in ebe5428be3ff4730cb1de788ca35ffdba223f379
