### ISSUE TITLE
File transfer

### ISSUE THREAD

**Issue by Bobscorn** [Bobscorn/ptop#16]
Implement a file transfer mechanism to allow one (or both) peer(s) to transfer a file to the other once successfully hole punched to each other
- [ ] One peer can transfer a file to the other
- [ ] (Optional) Both Peers can transfer files to the other
- [ ] (Optional) Works in both TCP and UDP

**Comment by DoubleCouponDay** [comment]
completed in commit eb75ddeca9edc80abf0ef53a7633b3d2c463646b
