### ISSUE TITLE
send strings between each peer

### ISSUE THREAD

**Issue by Bobscorn** [Bobscorn/ptop#5]

**Comment by Bobscorn** [comment]
Successfully hole punch and send strings to peers behind different NATs

- [x] Hole punches
  - [x] (Optional) Hole punches clients on the same machine
- [x] Authenticates both peers
- [x] Sends a string between hole punched peers

**Comment by DoubleCouponDay** [comment]
Completed in commit 221768fa9a8053d7ab643ab6e06c861c3d34e564
