### ISSUE TITLE
linux server aborts with double free

### ISSUE THREAD

**Issue by Bobscorn** [Bobscorn/ptop#9]
Linux server aborts with message `double free or corruption (out)`

Context:
Server had just successfully sent two peers hole punch messages,
Server then reset,
Server then received a new connection
Server receives message MY_DATA
Server DOES NOT receive READY_FOR_P2P, expected immediately after a MY_DATA message

Image:
![image](https://user-images.githubusercontent.com/25892420/147866710-8a55932c-16e4-4c5d-9faa-19615256f26d.png)

**Comment by DoubleCouponDay** [comment]
Order of operations to create this problem:

1. start linux server.
2. two tcp clients start and connect to the server.
3. both clients crash.
4. one client connects again.
5. server crashes with double free.
